sudo: false
language: ruby
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
before_install:
  - gem install bundler -v 1.14.6
  - cp -r spec/data/test.git spec/data/test/.git && cd spec/data/test && git checkout test.rb && cd -
